package com.zhxh.admin.misc;

public enum ErrorCode {
    ERROR_ADMIN_LOGIN_ACCOUNT_ERROR,
    ERROR_ADMIN_OLD_PASSWORD_ERROR,
    ERROR_ADMIN_LOGIN_ACCOUNT_DISABLED,
    ERROR_ADMIN_ROLE_CONTAINS_USERS,
}
